package com.mycompany.reto5g70.vista;

public class frmPrincipal extends javax.swing.JFrame {

    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tercerInforme = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        primerInforme = new javax.swing.JButton();
        segundoInforme = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(126, 224, 224));
        setPreferredSize(new java.awt.Dimension(450, 400));
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setText("Solución Reto 5: Presentado por Iván Rosero");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tercerInforme.setBackground(new java.awt.Color(153, 153, 255));
        tercerInforme.setText("Gererar Tercer Informe");
        tercerInforme.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tercerInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tercerInformeActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Mi PC (DESKTOP-5FJTMLD)\\Documents\\MinTic\\Ciclo2\\MisionTIC-2022-R2-Ciclo2-Programacion_Basica\\Ejercicios\\Reto5G70\\imagenes\\ast1.PNG")); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setMaximumSize(new java.awt.Dimension(250, 250));
        jLabel3.setMinimumSize(new java.awt.Dimension(250, 250));
        jLabel3.setPreferredSize(new java.awt.Dimension(379, 340));

        primerInforme.setBackground(new java.awt.Color(153, 153, 255));
        primerInforme.setText("Gererar Primer Informe");
        primerInforme.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        primerInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerInformeActionPerformed(evt);
            }
        });

        segundoInforme.setBackground(new java.awt.Color(153, 153, 255));
        segundoInforme.setText("Gererar Segundo Informe");
        segundoInforme.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        segundoInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundoInformeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Mi PC (DESKTOP-5FJTMLD)\\Documents\\MinTic\\Ciclo2\\MisionTIC-2022-R2-Ciclo2-Programacion_Basica\\Ejercicios\\Reto5G70\\imagenes\\utp.PNG")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tercerInforme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(segundoInforme, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(primerInforme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(primerInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(segundoInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tercerInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void primerInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerInformeActionPerformed
        new frmPrimerInforme().setVisible(true);
    }//GEN-LAST:event_primerInformeActionPerformed

    private void segundoInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundoInformeActionPerformed
        new frmSegundoInforme().setVisible(true);
    }//GEN-LAST:event_segundoInformeActionPerformed

    private void tercerInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tercerInformeActionPerformed
        new frmTercerInforme().setVisible(true);
    }//GEN-LAST:event_tercerInformeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton primerInforme;
    private javax.swing.JButton segundoInforme;
    private javax.swing.JButton tercerInforme;
    // End of variables declaration//GEN-END:variables
}
