#print("holap", "Ivan.", end="  ")
#print("holap", "Ivan.", end="\n")
#print("holap", end="")
#print("holap", "yo soy", "Ivan.", sep="-")
#print("holap","yo soy","Ivan.", sep=" ")

#print(0x123)
#print("Me gusta \"Monty Python\"")
#print('Me gusta "Monty Python')
#print(True > False)
#print(True < False)
#print('\"Estoy\" \n\"\"aprendiendo\"\" \n\"\"\"Python\"\"\'')

print(2 ** 3)
print(2 ** 3.)
print(2. ** 3)
print(2. ** 3.)
print(2 * 3.)
print(2. * 3)
print(2. * 3.)
print(6 / 3)
print(6 / 3.)
print(6. / 3)
print(6. / 3.)
print(6 // 3)
print(6 // 3.)
print(6. // 3)
print(6. // 3.)
print(6 // 4)
print(6. // 4)
print(-6 // 4)
print(6. // -4)
print(14%4.5)
print((5 * ((25 % 13) + 100) / (2 * 13)) // 2)
print((2**4), (2*4.), (2*4))
print((-2/4), (2/4), (2//4), (-2//4))
print((2%-4), (2%4), (2**3**2))